import OpenAI from "openai";
import type { GenerateScheduleInput, GenerateScheduleOutput, ShiftAssignment } from "@/types";

const openai = new OpenAI({ apiKey: process.env.OPENAI_API_KEY });

const SYSTEM_PROMPT = `You are ShiftIntel's AI scheduling engine. Your job is to generate optimal shift assignments for a workforce.

Given employees, coverage rules, and time-off requests, you must:
1. Meet minimum staffing requirements (min_employees) for each coverage rule slot
2. Respect employee availability and time-off requests
3. Minimize overtime (hours > 40/week per employee)
4. Distribute shifts fairly across eligible employees
5. Match required skills when specified
6. Prefer consistent shift patterns for employee satisfaction

Respond with a JSON array of shift assignments. Each assignment must have:
- employee_id: string
- department: string  
- start_time: ISO 8601 datetime
- end_time: ISO 8601 datetime
- break_minutes: number (30 for shifts > 6 hours)
- notes: optional string

Also include a summary object with coverage_score (0-100), total_hours, total_cost_usd, reasoning string, and warnings array.`;

async function generateWithRetry(input: GenerateScheduleInput, attempt = 1): Promise<GenerateScheduleOutput> {
  const prompt = `Generate an optimal schedule for the period ${input.period_start} to ${input.period_end}.

DEPARTMENTS: ${input.departments.join(", ")}

EMPLOYEES (${input.employees.length}):
${input.employees.map(e => 
  `- ${e.name} (ID: ${e.id}), Dept: ${e.department}, Rate: $${e.hourly_rate}/hr, MaxHrs: ${e.max_hours_per_week}, Skills: ${e.skills.join(", ")}`
).join("\n")}

COVERAGE RULES (${input.coverage_rules.length}):
${input.coverage_rules.map(r =>
  `- ${r.department}, ${["Sun","Mon","Tue","Wed","Thu","Fri","Sat"][r.day_of_week]}, ${r.start_time}-${r.end_time}, Min: ${r.min_employees} employees, Skills: ${r.required_skills.join(", ")}`
).join("\n")}

TIME OFF (${input.time_off_requests.filter(t => t.status === "approved").length} approved):
${input.time_off_requests
  .filter(t => t.status === "approved")
  .map(t => `- Employee ${t.employee_id}: ${t.start_date} to ${t.end_date} (${t.type})`)
  .join("\n") || "None"}

CONSTRAINTS: ${JSON.stringify(input.constraints || {})}

Return a JSON object with two keys:
1. "shifts": array of shift assignments
2. "summary": { coverage_score, total_hours, total_cost_usd, reasoning, warnings }`;

  try {
    const response = await openai.chat.completions.create({
      model: "gpt-4o",
      messages: [
        { role: "system", content: SYSTEM_PROMPT },
        { role: "user", content: prompt },
      ],
      response_format: { type: "json_object" },
      temperature: 0.2,
      max_tokens: 4000,
    });

    const content = response.choices[0].message.content;
    if (!content) throw new Error("Empty response from OpenAI");

    const parsed = JSON.parse(content);
    const shifts: ShiftAssignment[] = parsed.shifts || [];
    const summary = parsed.summary || {};

    // Calculate cost from employee rates
    let calculatedCost = 0;
    for (const shift of shifts) {
      const employee = input.employees.find(e => e.id === shift.employee_id);
      if (employee) {
        const hours = (new Date(shift.end_time).getTime() - new Date(shift.start_time).getTime()) / 3600000;
        const workHours = hours - (shift.break_minutes / 60);
        calculatedCost += workHours * employee.hourly_rate;
      }
    }

    return {
      shifts,
      coverage_score: summary.coverage_score || 0,
      total_hours: summary.total_hours || 0,
      total_cost_usd: calculatedCost || summary.total_cost_usd || 0,
      reasoning: summary.reasoning || "Schedule generated by AI",
      warnings: summary.warnings || [],
    };
  } catch (error) {
    if (attempt < 3) {
      await new Promise(r => setTimeout(r, 1000 * attempt));
      return generateWithRetry(input, attempt + 1);
    }
    throw error;
  }
}

export async function generateSchedule(input: GenerateScheduleInput): Promise<GenerateScheduleOutput> {
  return generateWithRetry(input);
}